/*
 * ECE 153B - Winter 2020
 *
 * Name(s): Norman Chung, Andrew Lu
 * Section: Wed 7-9:50 PM
 * Lab: 1B
 */

#include "LED.h"

void LED_Init(void) {
	// Enable GPIO Clocks
	RCC -> AHB2ENR |= RCC_AHB2ENR_GPIOAEN;
	RCC -> AHB2ENR |= RCC_AHB2ENR_GPIOBEN;
	RCC -> AHB2ENR |= RCC_AHB2ENR_GPIOCEN;
	RCC -> AHB2ENR |= RCC_AHB2ENR_GPIODEN;
	RCC -> AHB2ENR |= RCC_AHB2ENR_GPIOEEN;
	RCC -> AHB2ENR |= RCC_AHB2ENR_GPIOHEN;
	
	// Initialize Red LED on STM32 Board
	GPIOB -> MODER |= GPIO_MODER_MODE2_0;
	GPIOB -> MODER &= ~GPIO_MODER_MODE2_1;
	GPIOB -> OTYPER &= ~GPIO_OTYPER_OT2;
	GPIOB -> PUPDR &= ~GPIO_PUPDR_PUPD2_0;
	GPIOB -> PUPDR &= ~GPIO_PUPDR_PUPD2_1;

	// PB3, PA5, PD0 - Up
	GPIOB -> MODER |= GPIO_MODER_MODE3_0;
	GPIOB -> MODER &= ~GPIO_MODER_MODE3_1;
	GPIOB -> OTYPER &= ~GPIO_OTYPER_OT3;
	GPIOB -> PUPDR &= ~GPIO_PUPDR_PUPD3_0;
	GPIOB -> PUPDR &= ~GPIO_PUPDR_PUPD3_1;

	GPIOA -> MODER |= GPIO_MODER_MODE5_0;
	GPIOA -> MODER &= ~GPIO_MODER_MODE5_1;
	GPIOA -> OTYPER &= ~GPIO_OTYPER_OT5;
	GPIOA -> PUPDR &= ~GPIO_PUPDR_PUPD5_0;
	GPIOA -> PUPDR &= ~GPIO_PUPDR_PUPD5_1;

	GPIOD -> MODER |= GPIO_MODER_MODE0_0;
	GPIOD -> MODER &= ~GPIO_MODER_MODE0_1;
	GPIOD -> OTYPER &= ~GPIO_OTYPER_OT0;
	GPIOD -> PUPDR &= ~GPIO_PUPDR_PUPD0_0;
	GPIOD -> PUPDR &= ~GPIO_PUPDR_PUPD0_1;

	// PC14, PC15, PH0 - Down
	GPIOC -> MODER |= GPIO_MODER_MODE14_0;
	GPIOC -> MODER &= ~GPIO_MODER_MODE14_1;
	GPIOC -> OTYPER &= ~GPIO_OTYPER_OT14;
	GPIOC -> PUPDR &= ~GPIO_PUPDR_PUPD14_0;
	GPIOC -> PUPDR &= ~GPIO_PUPDR_PUPD14_1;

	GPIOC -> MODER |= GPIO_MODER_MODE15_0;
	GPIOC -> MODER &= ~GPIO_MODER_MODE15_1;
	GPIOC -> OTYPER &= ~GPIO_OTYPER_OT15;
	GPIOC -> PUPDR &= ~GPIO_PUPDR_PUPD15_0;
	GPIOC -> PUPDR &= ~GPIO_PUPDR_PUPD15_1;

	GPIOH -> MODER |= GPIO_MODER_MODE0_0;
	GPIOH -> MODER &= ~GPIO_MODER_MODE0_1;
	GPIOH -> OTYPER &= ~GPIO_OTYPER_OT0;
	GPIOH -> PUPDR &= ~GPIO_PUPDR_PUPD0_0;
	GPIOH -> PUPDR &= ~GPIO_PUPDR_PUPD0_1;

	// PH1, PE11, PE10 - Left
	GPIOH -> MODER |= GPIO_MODER_MODE1_0;
	GPIOH -> MODER &= ~GPIO_MODER_MODE1_1;
	GPIOH -> OTYPER &= ~GPIO_OTYPER_OT1;
	GPIOH -> PUPDR &= ~GPIO_PUPDR_PUPD1_0;
	GPIOH -> PUPDR &= ~GPIO_PUPDR_PUPD1_1;

	GPIOE -> MODER |= GPIO_MODER_MODE11_0;
	GPIOE -> MODER &= ~GPIO_MODER_MODE11_1;
	GPIOE -> OTYPER &= ~GPIO_OTYPER_OT11;
	GPIOE -> PUPDR &= ~GPIO_PUPDR_PUPD11_0;
	GPIOE -> PUPDR &= ~GPIO_PUPDR_PUPD11_1;

	GPIOE -> MODER |= GPIO_MODER_MODE10_0;
	GPIOE -> MODER &= ~GPIO_MODER_MODE10_1;
	GPIOE -> OTYPER &= ~GPIO_OTYPER_OT10;
	GPIOE -> PUPDR &= ~GPIO_PUPDR_PUPD10_0;
	GPIOE -> PUPDR &= ~GPIO_PUPDR_PUPD10_1;

	// PE12, PE13, PE14 - Right
	GPIOE -> MODER |= GPIO_MODER_MODE12_0;
	GPIOE -> MODER &= ~GPIO_MODER_MODE12_1;
	GPIOE -> OTYPER &= ~GPIO_OTYPER_OT12;
	GPIOE -> PUPDR &= ~GPIO_PUPDR_PUPD12_0;
	GPIOE -> PUPDR &= ~GPIO_PUPDR_PUPD12_1;

	GPIOE -> MODER |= GPIO_MODER_MODE13_0;
	GPIOE -> MODER &= ~GPIO_MODER_MODE13_1;
	GPIOE -> OTYPER &= ~GPIO_OTYPER_OT13;
	GPIOE -> PUPDR &= ~GPIO_PUPDR_PUPD13_0;
	GPIOE -> PUPDR &= ~GPIO_PUPDR_PUPD13_1;
	
	GPIOE -> MODER |= GPIO_MODER_MODE14_0;
	GPIOE -> MODER &= ~GPIO_MODER_MODE14_1;
	GPIOE -> OTYPER &= ~GPIO_OTYPER_OT14;
	GPIOE -> PUPDR &= ~GPIO_PUPDR_PUPD14_0;
	GPIOE -> PUPDR &= ~GPIO_PUPDR_PUPD14_1;
	
	// Initialize Green LED
	GPIOE -> MODER |= GPIO_MODER_MODE8_0;
	GPIOE -> MODER &= ~GPIO_MODER_MODE8_1;
	GPIOE -> OTYPER &= ~GPIO_OTYPER_OT8;
	GPIOE -> PUPDR &= ~GPIO_PUPDR_PUPD8_0;
	GPIOE -> PUPDR &= ~GPIO_PUPDR_PUPD8_1;
}

void Red_LED_Off(void) {
	GPIOB -> ODR &= ~GPIO_ODR_OD2;
}

void Red_LED_On(void) {
	GPIOB -> ODR |= GPIO_ODR_OD2;
}

void Red_LED_Toggle(void){
	GPIOB -> ODR ^= GPIO_ODR_OD2;
}

void Up_LED_On(void) {
	// PB3, PA5, PD0 - Up
	GPIOB -> ODR |= GPIO_ODR_OD3;
	GPIOA -> ODR |= GPIO_ODR_OD5;
	GPIOD -> ODR |= GPIO_ODR_OD0;
}

void Up_LED_Off(void) {
	// PB3, PA5, PD0 - Up
	GPIOB -> ODR &= ~GPIO_ODR_OD3;
	GPIOA -> ODR &= ~GPIO_ODR_OD5;
	GPIOD -> ODR &= ~GPIO_ODR_OD0;
}

void Down_LED_On(void) {
	// PC14, PC15, PH0 - Down
	GPIOC -> ODR |= GPIO_ODR_OD14;
	GPIOC -> ODR |= GPIO_ODR_OD15;
	GPIOH -> ODR |= GPIO_ODR_OD0;
}

void Down_LED_Off(void) {
	// PC14, PC15, PH0 - Down
	GPIOC -> ODR &= ~GPIO_ODR_OD14;
	GPIOC -> ODR &= ~GPIO_ODR_OD15;
	GPIOH -> ODR &= ~GPIO_ODR_OD0;
}

void Left_LED_On(void) {
	// PH1, PE11, PE10 - Left
	GPIOH -> ODR |= GPIO_ODR_OD1;
	GPIOE -> ODR |= GPIO_ODR_OD11;
	GPIOE -> ODR |= GPIO_ODR_OD10;
}

void Left_LED_Off(void) {
	// PH1, PE11, PE10 - Left
	GPIOH -> ODR &= ~GPIO_ODR_OD1;
	GPIOE -> ODR &= ~GPIO_ODR_OD11;
	GPIOE -> ODR &= ~GPIO_ODR_OD10;
}

void Right_LED_On(void) {
	// PE12, PE13, PE14 - Right
	GPIOE -> ODR |= GPIO_ODR_OD12;
	GPIOE -> ODR |= GPIO_ODR_OD13;
	GPIOE -> ODR |= GPIO_ODR_OD14;
}

void Right_LED_Off(void) {
	// PE12, PE13, PE14 - Right
	GPIOE -> ODR &= ~GPIO_ODR_OD12;
	GPIOE -> ODR &= ~GPIO_ODR_OD13;
	GPIOE -> ODR &= ~GPIO_ODR_OD14;
}

void Green_LED_Off(void) {
	GPIOE -> ODR &= ~GPIO_ODR_OD8;
}

void Green_LED_On(void) {
	GPIOE -> ODR |= GPIO_ODR_OD8;
}

void Green_LED_Toggle(void) {
	GPIOE -> ODR ^= GPIO_ODR_OD8;
}
